# Generated by Django 2.0.5 on 2018-05-04 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0002_auto_20180504_1648'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('eletronico', 'data', 'aula')},
        ),
    ]
