# Generated by Django 2.0.5 on 2018-05-04 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0003_auto_20180504_1702'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='eletronico',
            field=models.ForeignKey(on_delete=False, to='meu.Aparelho'),
        ),
    ]
