# Generated by Django 2.0.5 on 2018-05-04 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0005_auto_20180504_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='eletronico',
            field=models.CharField(max_length=30, verbose_name='Tecnologia'),
        ),
    ]
