# Generated by Django 2.0.5 on 2018-05-04 23:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0006_auto_20180504_2029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='eletronico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meu.Aparelho'),
        ),
    ]
