# Generated by Django 2.0.5 on 2018-05-05 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0007_auto_20180504_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='eletronico',
            field=models.CharField(max_length=30),
        ),
    ]
