# Generated by Django 2.0.5 on 2018-05-07 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0010_auto_20180507_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='aula',
            field=models.CharField(default='1ª aula', max_length=9, verbose_name='Aula'),
        ),
    ]
