# Generated by Django 2.0.5 on 2018-05-07 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0011_auto_20180507_2017'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Agenda',
            new_name='Agenda_m1',
        ),
    ]
