# Generated by Django 2.0.5 on 2018-05-07 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0012_auto_20180507_2024'),
    ]

    operations = [
        migrations.CreateModel(
            name='Agenda_m2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eletronico', models.CharField(max_length=30)),
                ('data', models.DateField(verbose_name='Data')),
                ('aula', models.CharField(default='1ª aula', max_length=9, verbose_name='Aula')),
                ('nome', models.CharField(max_length=50)),
                ('tema', models.CharField(max_length=30)),
                ('objetivo', models.TextField()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='agenda_m2',
            unique_together={('eletronico', 'data', 'aula')},
        ),
    ]
