# Generated by Django 2.0.5 on 2018-05-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0013_auto_20180507_2033'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda_m2',
            name='aula',
            field=models.CharField(default='2ª aula', max_length=9, verbose_name='Aula'),
        ),
    ]
