# Generated by Django 2.0.5 on 2018-05-13 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0015_auto_20180507_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda',
            name='escola',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='agenda',
            name='aula',
            field=models.CharField(choices=[('Matutino', (('am', '1ª aula matutino'), ('bm', '2ª aula matutino'), ('cm', '3ª aula matutino'), ('dm', '4ª aula matutino'), ('em', '5ª aula matutino'), ('fm', '6ª aula matutino'))), ('Vespertino', (('gv', '1ª aula vespertino'), ('hv', '2ª aula vespertino'), ('iv', '3ª aula vespertino'), ('jv', '4ª aula vespertino'), ('lv', '5ª aula vespertino'), ('mv', '6ª aula vespertino')))], max_length=3, verbose_name='Aula'),
        ),
    ]
