# Generated by Django 2.0.5 on 2018-05-13 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0016_auto_20180513_1703'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='agenda',
            unique_together={('eletronico', 'data', 'aula', 'escola')},
        ),
    ]
