# Generated by Django 2.0.5 on 2018-05-14 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0019_auto_20180514_1517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparelho',
            name='escola',
            field=models.CharField(max_length=50),
        ),
    ]
