# Generated by Django 2.0.5 on 2018-05-21 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0020_auto_20180514_1838'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='dias',
            field=models.IntegerField(default=1),
        ),
    ]
