# Generated by Django 2.0.5 on 2020-02-29 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0021_escola_dias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='aula',
            field=models.CharField(choices=[('Matutino', (('am', '1ª aula matutino'), ('bm', '2ª aula matutino'), ('cm', '3ª aula matutino'), ('dm', '4ª aula matutino'), ('em', '5ª aula matutino'), ('fm', '6ª aula matutino'), ('x', 'campo anulado'))), ('Vespertino', (('gv', '1ª aula vespertino'), ('hv', '2ª aula vespertino'), ('iv', '3ª aula vespertino'), ('jv', '4ª aula vespertino'), ('lv', '5ª aula vespertino'), ('mv', '6ª aula vespertino'))), ('Noturno', (('nn', '1ª aula noturno'), ('on', '2ª aula noturno'), ('pn', '3ª aula noturno'), ('qn', '4ª aula noturno'), ('rn', '5ª aula noturno')))], max_length=3, verbose_name='Aula'),
        ),
        migrations.AlterField(
            model_name='aparelho',
            name='nome',
            field=models.CharField(max_length=150),
        ),
    ]
