# Generated by Django 2.0.5 on 2020-02-29 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0022_auto_20200229_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aparelho',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
