# Generated by Django 2.0.5 on 2020-02-29 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0024_auto_20200229_1412'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='eletronico',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='aparelho',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
