# Generated by Django 2.0.5 on 2020-04-03 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0025_auto_20200229_1420'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mensagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(verbose_name='Data:')),
                ('titulo', models.CharField(max_length=40, verbose_name='Título: ')),
                ('escola', models.CharField(max_length=50, verbose_name='Escola: ')),
                ('texto', models.TextField(verbose_name='Descrição: ')),
            ],
        ),
    ]
