# Generated by Django 2.0.5 on 2020-04-05 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0026_mensagem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mensagem',
            options={'ordering': ('data',)},
        ),
        migrations.AddField(
            model_name='aparelho',
            name='permicao',
            field=models.BooleanField(default=False),
        ),
    ]
