# Generated by Django 2.0.5 on 2020-04-05 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0027_auto_20200405_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aparelho',
            name='permicao',
        ),
        migrations.AddField(
            model_name='escola',
            name='permicao',
            field=models.BooleanField(default=False),
        ),
    ]
