# Generated by Django 2.0.5 on 2020-04-05 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0028_auto_20200405_1714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='permicao',
            field=models.BooleanField(default=False, verbose_name='Permitir botão de agendar todas as aula'),
        ),
        migrations.AlterField(
            model_name='mensagem',
            name='texto',
            field=models.TextField(blank=True, verbose_name='Descrição: '),
        ),
    ]
