# Generated by Django 2.0.5 on 2020-04-08 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0029_auto_20200405_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='escola',
            name='permicao_mensagem',
            field=models.BooleanField(default=False, verbose_name='Permitir  acessar mensagem'),
        ),
        migrations.AddField(
            model_name='escola',
            name='permicao_ninja',
            field=models.BooleanField(default=False, verbose_name='Permitir de aula fixa'),
        ),
        migrations.AlterField(
            model_name='agenda',
            name='aula',
            field=models.CharField(choices=[('Matutino', (('am', '1ª aula matutino'), ('bm', '2ª aula matutino'), ('cm', '3ª aula matutino'), ('dm', '4ª aula matutino'), ('em', '5ª aula matutino'), ('fm', '6ª aula matutino'))), ('Vespertino', (('gv', '1ª aula vespertino'), ('hv', '2ª aula vespertino'), ('iv', '3ª aula vespertino'), ('jv', '4ª aula vespertino'), ('lv', '5ª aula vespertino'), ('mv', '6ª aula vespertino'))), ('Noturno', (('nn', '1ª aula noturno'), ('on', '2ª aula noturno'), ('pn', '3ª aula noturno'), ('qn', '4ª aula noturno'), ('rn', '5ª aula noturno')))], max_length=3, verbose_name='Aula'),
        ),
    ]
