# Generated by Django 2.0.5 on 2020-04-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meu', '0030_auto_20200408_1236'),
    ]

    operations = [
        migrations.AlterField(
            model_name='escola',
            name='permicao_mensagem',
            field=models.BooleanField(default=False, verbose_name='Permição de visualizar mensagens '),
        ),
        migrations.AlterField(
            model_name='escola',
            name='permicao_ninja',
            field=models.BooleanField(default=False, verbose_name='Permição de fixar aulas '),
        ),
    ]
